<div class="fullwidth-template">
    @include('clients.trangchus.components.slideshow')
    @include('clients.trangchus.components.service')
    @include('clients.trangchus.components.banner1')
    @include('clients.trangchus.components.promotionalproduct')
    @include('clients.trangchus.components.banner2')
    @include('clients.trangchus.components.category')
    @include('clients.trangchus.components.featuredproduct')
    @include('clients.trangchus.components.bestseller')
    @include('clients.trangchus.components.banner3')
    @include('clients.trangchus.components.starproduct')
    @include('clients.trangchus.components.fromourblog')
    @include('clients.trangchus.components.brand')
    @include('clients.components.modalhome')
</div>